### Site Settings ###
baseurl: "" # Site está em heflerdev.github.io, então mantemos vazio
repository: heflerdev/heflerdev.github.io
remote_theme: yousinix/portfolYOU
open_new_tab: true
title: Henrique Hefler
description: Backend Developer · DevOps Engineer · Microservices & AWS Specialist
url: "https://heflerdev.github.io"

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**

### Author Info ###
author:
  name: Henrique Hefler
  image: "https://media.licdn.com/dms/image/v2/C4E03AQGT0IJ9Kyocgw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1566413192270?e=1753920000&v=beta&t=SEUY7uWnRufTPpyBJFBlq3FvrJMGGcv6gET6FMEsFHQ"
  email: heflerdev@gmail.com
  github: heflerdev
  linkedin: heflerdev
  twitter: heflerdev
  # Adicione mais redes se quiser (ex: instagram, youtube, etc.)

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true

### Disqus ###
disqus:
  shortname: # Deixe vazio ou remova se não for usar comentários

### Analytics ###
analytics:
  enabled: true
  google:
    tracking_id: G-XXXXXXXXXX # Substitua por seu código do Google Analytics

### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username: heflerdev
  color: "#d73a49"
  message: "Thank you for visiting."
  description: "Support my work!"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
